apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "toxi.tech.claudioed/v1alpha1",
          "kind": "Killer",
          "metadata": {
            "name": "players-killer"
          },
          "spec": {
            "rule": {
              "duration": "15s"
            },
            "selector": {
              "matchLabels": {
                "app": "players",
                "version": "v1"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v0.19.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: toxi-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Killer is the Schema for the killers API
      kind: Killer
      name: killers.toxi.tech.claudioed
      version: v1alpha1
  description: Operator to help Chaos Testing
  displayName: toxi-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          - pods
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - toxi.tech.claudioed
          resources:
          - killers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - toxi.tech.claudioed
          resources:
          - killers/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: toxi-operator-manager-role
      - rules:
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: toxi-operator-proxy-role
      - rules:
        - nonResourceURLs:
          - /metrics
          verbs:
          - get
        serviceAccountName: toxi-operator-metrics-reader
      deployments:
      - name: toxi-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: claudioed/toxi-operator:latest
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: toxi-operator-leader-election-role
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - chaos
  - killer
  - engineering
  links:
  - name: Toxi Operator
    url: https://toxi-operator.domain
  maturity: alpha
  provider:
    name: claudioed
  version: 0.0.1
