# permissions for end users to view killers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: killer-viewer-role
rules:
- apiGroups:
  - toxi.tech.claudioed
  resources:
  - killers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - toxi.tech.claudioed
  resources:
  - killers/status
  verbs:
  - get
