apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v0.19.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: toxi-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Killer is the Schema for the killers API
      kind: Killer
      name: killers.toxi.tech.claudioed
      version: v1alpha1
  description: Operator to help Chaos Testing
  displayName: toxi-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - chaos
  - killer
  - engineering
  links:
  - name: Toxi Operator
    url: https://toxi-operator.domain
  maturity: alpha
  provider:
    name: claudioed
  version: 0.0.0
